"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = __importDefault(require("express"));
const userController_1 = require("../controllers/userController");
const router = express_1.default.Router();
router.post("/check-email-exists", userController_1.userController.checkEmailExists);
router.post("/login", userController_1.userController.login);
router.post("/signup", userController_1.userController.signup);
router.post("/confirm-user", userController_1.userController.confirmUser);
router.get("/check-user-exists", userController_1.userController.checkUserExists);
router.post("/resend-confirmation", userController_1.userController.resendConfirmation);
router.post("/send-code", userController_1.userController.sendCode);
router.post("/resend-code", userController_1.userController.resendCode);
router.post("/confirm-phone-number", userController_1.userController.confirmPhoneNumber);
router.post("/forgot-password", userController_1.userController.forgotPassword);
router.post("/confirm-otp", userController_1.userController.confirmOtp);
router.post("/change-password", userController_1.userController.changePassword);
router.post("/set-new-password", userController_1.userController.setNewPassword);
exports.default = router;
